# Describes the format for available climate services

set_aux_heat:
  description: Turn auxiliary heater on/off for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    aux_heat:
      description: New value of axillary heater.
      example: true
set_away_mode:
  description: Turn away mode on/off for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    away_mode:
      description: New value of away mode.
      example: true
set_hold_mode:
  description: Turn hold mode for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    hold_mode:
      description: New value of hold mode
      example: 'away'
set_temperature:
  description: Set target temperature of climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    temperature:
      description: New target temperature for HVAC.
      example: 25
    target_temp_high:
      description: New target high tempereature for HVAC.
      example: 26
    target_temp_low:
      description: New target low temperature for HVAC.
      example: 20
    operation_mode:
      description: Operation mode to set temperature to. This defaults to current_operation mode if not set, or set incorrectly.
      example: 'Heat'
set_humidity:
  description: Set target humidity of climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    humidity:
      description: New target humidity for climate device.
      example: 60
set_fan_mode:
  description: Set fan operation for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.nest'
    fan_mode:
      description: New value of fan mode.
      example: On Low
set_operation_mode:
  description: Set operation mode for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.nest'
    operation_mode:
      description: New value of operation mode.
      example: Heat
set_swing_mode:
  description: Set swing operation for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.nest'
    swing_mode:
      description: New value of swing mode.
      example:

turn_on:
  description: Turn climate device on.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'

turn_off:
  description: Turn climate device off.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'

ecobee_set_fan_min_on_time:
  description: Set the minimum fan on time.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    fan_min_on_time:
      description: New value of fan min on time.
      example: 5

ecobee_resume_program:
  description: Resume the programmed schedule.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    resume_all:
      description: Resume all events and return to the scheduled program. This default to false which removes only the top event.
      example: true

mill_set_room_temperature:
  description: Set Mill room temperatures.
  fields:
    room_name:
      description: Name of room to change.
      example: 'kitchen'
    away_temp:
      description: Away temp.
      example: 12
    comfort_temp:
      description: Comfort temp.
      example: 22
    sleep_temp:
      description: Sleep temp.
      example: 17

nuheat_resume_program:
  description: Resume the programmed schedule.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'

sensibo_assume_state:
  description: Set Sensibo device to external state.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    state:
      description: State to set.
      example: 'idle'

broadlink_set_schedule:
  description: Set programmed schedule.
  fields:
    entity_id:
      description: Name of entities to change.
      example: 'climate.kitchen'
    week_start_1:
      description: Name of entities to change.
      example: 'climate.kitchen'
    week_stop_1:
      description: Name of entities to change.
      example: 'climate.kitchen'
    week_start_2:
      description: Name of entities to change.
      example: 'climate.kitchen'
    week_stop_2:
      description: Name of entities to change.
      example: 'climate.kitchen'
    week_start_3:
      description: Name of entities to change.
      example: 'climate.kitchen'
    week_stop_3:
      description: Name of entities to change.
      example: 'climate.kitchen'
    weekend_start:
      description: Name of entities to change.
      example: 'climate.kitchen'
    weekend_stop:
      description: Name of entities to change.
      example: 'climate.kitchen'
    away_temp:
      description: Name of entities to change.
      example: 'climate.kitchen'
    home_temp:
      description: Name of entities to change.
      example: 'climate.kitchen'


broadlink_set_advanced_conf:
  description: Set thermostat advanced conf.
  fields:
    entity_id:
      description: Name of entities to change.
      example: 'climate.kitchen'
    loop_mode:
      description: 0 means Saturday and Sunday follow the "weekend" schedule, 1 means only Sunday follow the "weekend" schedule, 2 means every day follows the "weekday" schedule.
      example: '0'
    osv:
      description: Set temperature range for external sensor. 5 to 99.. Factory default = 42.
      example: '42'
    dif:
      description: Deadzone for floor temprature. 1 to 9. Factory default = 2
      example: '2'
    svh:
      description: Upper temperature limit for internal sensor. 5 to 99. Factory default = 35.
      example: '35'
    svl:
      description: Lower temperature limit for internal sensor. 5 to 99. Factory default = 5.
      example: '5'
    freeze:
      description: Anti-freezing function 0 for anti-freezing function shut down, 1 for anti-freezing function open. Factory default = 0
      example: '0'
    adj:
      description: Actual temperature calibration. Prescision 0.1.
      example: '0.1'
    pon:
      description: Power on memory. 0 for power on memory off, 1 for power on memory on. Factory default = 0
      example: '0'
    sen:
      description: Sensor mode. 0 for internal sensor, 1 for external sensor, 2 for internal control temperature, external limit temperature. Factory default = 0.
      example: '0'